### ISSUE TITLE
It doesn't seem to work properly

### ISSUE THREAD

**Issue by boomxiao** [thedevslot/WhatATheme#20]
https://thedevslot.com/WhatATheme/

**Comment by liuzhenyu-yyy** [comment]
Same problems here. The page looks good in Safari but doesn't work properly for Microsoft Edge.

**Comment by boomxiao** [comment]
I found out why it's not working:you can find "@import url('https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css')"in file named "main.scss",you can't open this url in china，so you can download this css file and import it,then  it will work.

**Comment by liuzhenyu-yyy** [comment]
That solved the problem, thanks.
