### ISSUE TITLE
Is there a way to add a new social network emoji?

### ISSUE THREAD

**Issue by ouafabulous** [thedevslot/WhatATheme#30]
If I understood well, the html files get generated on the fly. Hence it is a bit complicated to add/edit the visuals on the page.

Can you help me please have a hand on that? Thank you in advance

**Comment by harsh98trivedi** [comment]
Hi @ouafabulous, I'm sorry for the delayed response. I totally understand that it looks a bit complicated to add/edit the visuals on the page but it is pretty easy to do that. You can use FontAwesome icons to add any of the social media icons you want, but for that, you'll b needing some knowledge of HTML. If you want I can surely help you out adding any of the content that you require to a fork of WhatATheme.
