### ISSUE TITLE
Error While running

### ISSUE THREAD

**Issue by Rasesh2005** [thedevslot/WhatATheme#5]
When I Try To host locally using `bundle exec jekyll run` The Following Error Appears,
Attachment Showing My Result:
![Capture2](https://user-images.githubusercontent.com/65321291/103339539-9f726400-4aa7-11eb-8450-8fe4efc5f329.PNG)

 I don't Have Any Knowledge about Ruby, But Felt the template amazing.. Please Help me Execute the template...

**Comment by harsh98trivedi** [comment]
Hi @Rasesh2005, did you run the command `bundle install` before executing `bundle exec jekyll s`?

**Comment by Rasesh2005** [comment]
Yes I did `bundle install` and when i did `bundle exec jekyll s`, this error popped up

**Comment by Rasesh2005** [comment]
Aah!! just found that it doesn't work on 32-bit Windows, It works perfectly on 64 bit

**Comment by harsh98trivedi** [comment]
Great! 😄
